### ISSUE TITLE
Unicode not normalised

### ISSUE THREAD

**Issue by olesar** [UniversalDependencies/UD_Old_Russian-RNC#1]
@dan-zeman,

In some new piece of data, validate.py reports the following:
Unicode not normalized: LEMMA.character[0] is CYRILLIC SMALL LETTER IE, should be CYRILLIC SMALL LETTER IE WITH GRAVE.
Unicode not normalized: FORM.character[0] is CYRILLIC SMALL LETTER O, should be CYRILLIC SMALL LETTER O WITH DIAERESIS.
Unicode not normalized: FORM.character[0] is CYRILLIC CAPITAL LETTER O, should be CYRILLIC CAPITAL LETTER O WITH DIAERESIS.

Although this could be a typo, what should we do if we want to keep the source data as is?

**Comment by dan-zeman** [comment]
Unicode normalization error is not a typo. It means that there are multiple ways how to digitally encode the same text, one of them is defined in the Unicode standard as canonical but the data contain non-canonical encoding.

The validator reports the first character position where the actual encoding differs from the normalized form. However, it usually means that at least one subsequent position also differs, otherwise it would not be possible to preserve the source text.

Unicode normalization can be easily fixed using the script [normalize_unicode.pl](https://github.com/UniversalDependencies/tools/blob/master/normalize_unicode.pl) from the tools repository.
